services:
  app:
    build:
      context: .
      dockerfile: "./prod.dockerfile"
    ports:
      - 8080:3000
    env_file:
      - ./backend/.env
    command: ["run", "start"]
    depends_on:
      - postgres
  postgres:
    image: "postgres:17"
    env_file:
      - ./backend/.env
    volumes:
      - b-and-f:/var/lib/postgresql/data
volumes:
  b-and-f: